### ISSUE TITLE
GTS files output by wis2-to-gts-gateway

### ISSUE THREAD

**Issue by shirley-xuelei** [wmo-im/wis2-transition-guide#57]
Take the SYNOP data for instance, currently, wis2-to-gts-gateway receives data files from WIS2 in three different granularities,
1. single subset
2. a bulletin contains multiple subsets
3. multiple bulletins with multiple subsets each

There are two strategies for the wis2-to-gts-gateway to output,
1. forward the files directly
problem:  1) there will be several different data files sent to the GTS with the same 'TTAAii CCCC',  so there maybe a risk that the MSS and/or the domestic systems in some countries will take those files as duplicated and discard them.
2. re-organize all the files into regular single bulletins with multiple subsets，then pack them according to different CCCC.
problem：1) the function of the gateway will be more complex.  2) If the subsets with the same 'TTAAii CCCC' cannot arrive completely within the time window of the encoding, it also faces the above problem of using the same header for two different files.

So, 
1. the 1st question, which strategy shall we choose?
2. the 2nd question, does it matter if different files sent to GTS have the same header?
3. the 3rd question, what if the header in the gts.propertis is inconsistent with the header in the data? Can we prioritize the header in the data file and use the gts.properties only when there is no header in the data?

**Comment by shirley-xuelei** [comment]
@golfvert @6a6d74 @hhaddouch @chenxiaoxia2019 
The questions raised at yesterday's meeting. Please review.

**Comment by golfvert** [comment]
I'd suggest organising a call with GTS experts to have their feedback. 
@shirley-xuelei what is the take of your GTS experts on this ?
@6a6d74 Do you know the implementation approach of the UK Gateway ? I assume you liaised with IBL on this.
@hhaddouch can you contact a few GTS experts (eg. Weiqing, Kenji, Jan -IBL-...) ? I could ask David Podeur at Météo-France to join as well.
Then we have a Teams session of the Implementation and Transition ET plus those experts to decide the way forward.

**Comment by shirley-xuelei** [comment]
> I'd suggest organising a call with GTS experts to have their feedback. @shirley-xuelei what is the take of your GTS experts on this ? @6a6d74 Do you know the implementation approach of the UK Gateway ? I assume you liaised with IBL on this. @hhaddouch can you contact a few GTS experts (eg. Weiqing, Kenji, Jan -IBL-...) ? I could ask David Podeur at Météo-France to join as well. Then we have a Teams session of the Implementation and Transition ET plus those experts to decide the way forward.

**Comment by shirley-xuelei** [comment]
1. We tend to rename the filename with the pattern of 'CCCCnnnnnnnn.[a|b|f]'（CCCC is from the gts.properties）and forward them to GTS directly, without 'cat' nor 'split'. Of course, the gateway should follow the mechanism of whitelist, and should validate the GTS header and envelop info. in the original files, if the are missing, the gateway should make the supplement.
2. For us, our GTS system can distinguish different bulletins with the same header, that is to say, we won't take them as the duplicated data.
3. In my opinion, the priority of the header in the file should be higher than the one in gts.properties.
@golfvert @6a6d74 @hhaddouch

**Comment by golfvert** [comment]
As I often repeat, WIS2 is data agnostic. It is a set of pipes and what is in the pipe is irrelevant (for WIS2).
With this in mind:
1. For me, yes, you get something on WIS with gts.properties, you take it, whitelist it and then push it `unchanged` on the GTS
2. I'm not sure I understand...
3. In the "agnostic" logic, the gateway should NOT care about the header in the file by use solely gts.properties.

But, again, we need some GTS gurus to know what is doable and potentially to advise future users of the gateway feature to avoid potential troubles.

**Comment by hhaddouch** [comment]
I contacted some GTS experts, here below their proposals:
**Lemkhenter (Morocco)**

1- If the first proposal (transmit files directly) is the best suited for WIS2, we can solve the problem by:
We add the BBB (relative to the RRA, RRB, RRC delay, ...) to the header after transmitting the first file. The AMSS consider the BBB as part of the header and do not consider messages as duplicates. We can also act on the YYGGgg.
 
2- In my opinion the second proposal (reorganize all files into regular single bulletins with several subsets, then group them according to different CCCCs) could be modified to resemble the notion of compilation known in the AMSS. In this case we use "general naming" standardized in the GTS manual instead of working with headers.

**Weiqing Qu (Australia)**

From GTS gateway's view point, option 1 is obviously simple to implement. The concern of many files with same TTAAii CCCC might being treated as duplicates has some points there. But duplicate checking is normally based on the full header, namely "TTAAii CCCC YYGGgg [BBB]", not only TTAAii CCCC. Theoretically, any difference in the combination of those 4 groups in the header should be able avoid the file/message being treated as duplicates. One thing I can think of is that when the GTS gateway issue a bulletin out of WIS2 system, it can assign its own issue time (YYGGgg), which would distinguish the files with same TTAAii CCCC. This practice is not strictly conform to the GTS Manual, as the bulletin issue time for some observation indicates the standard times of observation, and is not the timestamp of the bulletins. But the real observation time is inside the report anyway. So this should not causing problem in processing the file. However, given every MSS is different, what said above is just a thought for further discussion.

**Jan Osusky (IBL)**

if I understand it right, the main problem is that some centres have changed not only the means of how they distribute the data but also the way they structure it. In other words, they stopped compiling meteorological reports from individual stations into bulletins. I appreciate the enthusiasm, but perhaps we could ask the centres to keep doing the collection/compilation until the migration is finished.
I am afraid that any partial solution like changing the YYGGgg will cause serious degradation of the service. The date/time group defined in the abbreviated heading line is often preferred over the observation time of individual reports. In addition, I am afraid that assigning "arbitrary" YYGGgg may cause data duplication or even loops. On the other hand, keeping the same TTAAii CCCC YYGGgg BBB is risky too, as Weiqing correctly noted. The centres that are not ready for WIS 2.0 use old systems, often in-house-made collections of scripts and cron jobs.
The alternative to it is that the WIS2 to GTS gateway completely overtakes this responsibility. Theoretically, it is known which observation reports belong to which bulletin, but help from the originating centres will be needed to set appropriate collection intervals and other parameters.
Of course, there is no need to do it for data that were never part of the GTS exchange, so the task might be smaller than it appears, however, as more centres will migrate more compilation rules will have to be configured on the WIS2 to GTS gateway. This brings me back to my first idea: "Please, keep compiling, do not break bulletins into individual reports at this stage."

**Ken Tsunda (Japan)**

I totally agree with Jan.
If my memory is collect, WIS2box will divide in to individual station numbers when wis2box feeds complied files into WIS2.0. As you may remember, Kai pointed this issue sometimes, and request at et-w2at to add a new option switch “do not divide complied file” into wis2box application. But I don’t know whether the option was installed yet.

**Comment by golfvert** [comment]
So, if I try to summarize what is written above, is that correct to include something like this in the Transition guide:
`Centres wishing to use the WIS2 to GTS capabilities MUST send on WIS2 the exact same file that they are currently sending on the GTS, and include in the notification messages the properties.gts value corresponding to their current practice on the GTS.`
The wording might not be exactly that, but, the idea is clear, I think.
Then, for the WIS2 to GTS Gateway we can also reiterate that:

`Centres operating WIS2 to GTS will relay whitelisted header solely using the properties.gts information in the notification message and without modifying the files received`.

Is that sufficient ? And consistent with the information from our GTS colleagues ?
